### ISSUE TITLE
request for removeAppender() function

### ISSUE THREAD

**Issue by ShawnTalbert** [aurelia/logging#32]
**I'm submitting a feature request**
* **Library Version:**
1.1.0

**Please tell us about your environment:**
* **Operating System:**
Linux (mint)

* **Node Version:**
6.9.1
* **Browser:**
all 
* **Language:**
TypeScript 2.0.9

**Expected/desired behavior:**

Would like to have a `removeAppender` companion to the `addAppender`

* **What is the motivation / use case for changing the behavior?**

I have a use case where I have a default appender assigned, and I'd like to remove the default  and replace it with a different appender.

**Comment by unional** [comment]
How would you like to identify the existing appender(s)?
Since the place your add the default appender and the place you want to swap the appender can be quite remote from each other, you may not be able to (or want to) access the existing appender(s).

Do you think `removeAppender(existingAppender)` would be sufficient?
