### ISSUE TITLE
Can we add a "trace" level?

### ISSUE THREAD

**Issue by diegograsso** [aurelia/logging#33]
**I'm submitting a feature request**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
5.10.0

* **NPM Version:**
3.8.3
* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
all

* **Language:**
all

**Current behavior:**
4 log levels supported

**Expected/desired behavior:**
Add a 5th level: trace

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
I would like adda an appender that has this level of logging.

**Comment by EisenbergEffect** [comment]
Can you clarify why you need another level and what you would call it?

**Comment by diegograsso** [comment]
Yes, I would call it "trace", like the method available on the console:
https://developer.mozilla.org/en-US/docs/Web/API/Console/trace
I know it's not standard but it's supported by all major browsers and node. It prints the message and adds the stack trace of the call, sometimes it's useful for debugging. We had it in our custom log library that I'm replacing by Aurelia's.

**Comment by EisenbergEffect** [comment]
If you would be willing to submit a PR, we could put this in.

**Comment by krisdages** [comment]
I have a similar requirement and I have made some customizations to be able to add arbitrary additional log levels with methods 
```
addCustomLevel(name, value) 
removeCustomLevel(name)
```

Resetting the configuration for testing was sort of difficult since LogManager is a singleton and there isn't currently a way to get the appenders list, so I added
```
getAppenders() {  return [...appenders]; }
clearAppenders() { ... }
```

It sounds like you are possibly redoing this library in TypeScript, but I could still submit a PR if you want.

**Comment by Alexander-Taran** [comment]
Can be closed?

**Comment by EisenbergEffect** [comment]
Covered by custom log levels.
