### ISSUE TITLE
1.3.0 fails in ES5 environment

### ISSUE THREAD

**Issue by ShawnTalbert** [aurelia/logging#38]
**I'm submitting a bug report**
* **Library Version:**
1.3.0

**Please tell us about your environment:**
* **Operating System:**
Linux 

* **Language:**
all

**Current behavior:**
`TypeError: Cannot find function assign in object function Object`

**Expected/desired behavior:**
The function `connectLoggers()` has been updated in commit 3b82212a8f211649c000f6a3f5f9f4c2468b3a15 to use `Object.assign` which seems to be an ES2015 feature. In my runtime (an ES5 environment) `Object.assign` is not defined hence the error above. I'm hoping we still support ES5?

**Comment by jods4** [comment]
I am to blame for this change.

Aurelia relies on a few ES5, 6 and even 7+ features and it comes with a minimum set of polyfills in `aurelia-polyfills`.

This library is automatically included and contains a polyfill for `Object.assign` here:
https://github.com/aurelia/polyfills/blob/master/src/object.js#L63

It makes me wonder why you get this error. I'll try to debug it.

**Comment by jods4** [comment]
I'll need more details to reproduce the problem.

I have used this project as basis: 
https://github.com/jods4/aurelia-webpack-build/tree/master/demos/01-No_splits
As you can see it uses `.developmentConsole()`.

I have added `es6-promise-promise` as a `Promise` polyfill and it runs fine in IE11 (which lacks `Object.assign`).

**Comment by ShawnTalbert** [comment]
I'm using aurelia-logging _on its own_, i.e. not inside an aurelia app.  Hence, I have no polyfills as this library previously needed none.

The modularity and no dependencies _were_ strengths of this library that allowed me to sell it to management for use in areas outside our Aurealia apps. It let us have a single consistent logging framework across browser and non-browser platforms.

Since we're talking about a single function, can we please make this lib ES5 compatible again (without ES2015), or is that `Object.assign()` implementation the only option?

**Comment by jods4** [comment]
Aurelia has a whole has always had a few polyfills requirements for older browser that are listed here: 
https://github.com/aurelia/polyfills

Some parts work with less but when coding we kind of assume that they are available.
It becomes difficult to manage the project if we need to list which Aurelia modules are ES3, ES5 or ES6 and develop/test accordingly. 

Moreover those new features come with benefits like smaller, cleaner or faster code, which is an important quality.

Of course, everything is possible and in this specific instance we could change the code to do a manual copy of the properties, i.e. a simplified local polyfill of sorts. 
Do we want to? _Personally_ I'd say no because it kind of defeats the purpose, takes time and resources, and is a step towards giving compatibility guarantees that we don't want to give. 

I would rather that you include `aurelia-polyfills` or your own `Object.assign` polyfill if you target ES5 browsers and use `aurelia-logging`.

@EisenbergEffect what do you think?

**Comment by EisenbergEffect** [comment]
I think we might want to add a section to the readme that says, "Either use aurelia-polyfills or include your own Object.observe polyfill."

**Comment by jods4** [comment]
PR #39

**Comment by ShawnTalbert** [comment]
Did anyone benchmark the _improved_ approach (that now uses Object.assign()) vs the previous code?

**Comment by jods4** [comment]
The interesting improvement is not `Object.assign` vs manual copy, it's using `Logger.prototype` rather than having fields on each individual logger instance.

As for `Object.assign` specifically, at this point it's pretty sure that it's slower than manual copy code (browsers are in the process of making their ES6 implementations faster, Chrome in particular has made large improvements). The `connectLoggers()` function only runs once, so its perf does not really matter. `Object.assign` is clearer, more concise and will be faster in future browser releases.

And that really, is the main point to me. I'm trying to bring Aurelia's size down and having clear, short code is the most important factor. 

Reverting the code (to make it larger/more complex), testing, publishing a new version... it all takes time, for very little benefit to Aurelia as a whole. 
On the other hand, you could `import "aurelia-polyfills"` and it will work. If you run Aurelia in legacy environments, that's what you're supposed to do.

That's my personal opinion, maybe other Aurelia members would think otherwise, @EisenbergEffect?

**Comment by jods4** [comment]
I would also like to add that since there has been no significant functional change to `aurelia-logging`, continuing to use `aurelia-logging@v.1.2.0` is also an option, as long as you support old browsers.

**Comment by ShawnTalbert** [comment]
Thanks @jods4.

I have rolled back to `1.2.0` but I think I was probably one of the people requesting the `removeAppender` enhancement in the first place. :\

 I think it is important to note this _is_ a breaking change as my code unexpectedly crashed after update. Perhaps this should be 2.0.0?

Any possibility to just use `Logger.prototype` in an ES5 compatible way? I shant belabor the issue any further. If the Aurealia team doesn't consider to consider ES5 and the previously standalone nature of the library as important then so be it. 

While I love Aurelia Framework, I  also love @EisenbergEffect's original stance with this module as entirely self-contained. That fact actually helped me sell it to management for use outside of just Aurelia apps.

p.s it's not an old browser I'm running on - it's an ES5 serverside runtime (NetSuite).

**Comment by jods4** [comment]
Any observable change can crash some code. For example if someone used `getOwnProperty` on the loggers to determine if they were connected, it wouldn't work anymore.

A reasonable definition of _breaking change_ is when the intended behavior on supported platforms changes between release.

The key here is that the supported platform for Aurelia includes `aurelia-polyfills`. It was lucky that `aurelia-logging` worked without before and I understand that it's unfortunate that it does not anymore, but nobody in the Aurelia team is actively testing compatibility with such platform.

Another key aspect here is that `Object.assign` is everywhere today. Support goes back _at least_ to Edge 12, FF 38, CH 47, OP 34, SF 9, Node 4, iOS 9. Widespread support means this impacts practically nobody.
https://kangax.github.io/compat-table/es6/#harmony-flag-note
I don't know what NetSuite runs on, but since it's a server-side component maybe you have enough control to upgrade? Node 4 is really not a recent release.

**Comment by ShawnTalbert** [comment]
If this library now requires `aurelia-polyfills` or depends on an ES2015 feature just to load, it's an obvious and reasonable 'breaking change' - at least to me. 

It's not _lucky_ that this library worked without it - it was independent by design. I'm surprised to see so much resistance to revert something like 5 lines of code that worked fine before?

I took a quick peek at the `readme.md` history and it appears the strong 'no dependencies' was quietly dropped in May of [last year](https://github.com/aurelia/logging/commit/8919a212d8d753a6e7303e59746613fb8f0a16b8)

So I guess that's the last I'll say on it. I'll guess I'm left to use a polyfill or permanently fork this repo.

**Comment by unional** [comment]
I would agree this is a breaking change. Just got surprised by this as I release a new package that uses this package. My package need to work on IE8+

**Comment by jods4** [comment]
@unional IE 8 is not a supported Aurelia target (_maybe_ it works, if it does -- good for you).
Import `aurelia-poylfills` and this package works in IE 9.

**Comment by unional** [comment]
I know. But if it does not require `aurelia-polyfills` in the past and now it does, it is a breaking change.

Consider a consumer is using `aurelia-logging` without `aurelia-polyfills`. When the consumer gets this new version, the application fail. It is a breaking change. A patch or minor version bump will not cause this breaking behavior.

**Comment by jods4** [comment]
I can relate but using `aurelia-logging` (or any part of Aurelia) without `aurelia-poylfills` on IE is not supported. 

In the same way that it _might_ work on IE 8, it _might_ have worked without polyfills, but this comes without guarantees and might break _at any point_.

Similarly, do you think we should do a major version bump if a library happened to work on IE 7 but suddenly does not anymore? We don't even test that and most likely we would not know!

Not using `aurelia-polyfills` in IE is the same: we don't test it and it's not supported. If it works, good for you. But if it breaks then you're on your own.

**Comment by unional** [comment]
Sorry about IE8. That's just noise. The same applies to IE 9/10/11.

@ShawnTalbert you can use https://github.com/rubennorte/es6-object-assign or https://github.com/BendingBender/object-assign-shim for script version.

**Comment by ShawnTalbert** [comment]
Thanks @unional. I'm disappointed that the breaking change was introduced at all as it is unnecessary and unjustified. It's breaking ES5 compatibility that's the big loss here; completely independent of any particular browser (indeed I'm not even using this library in a browser).
